# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# set working directory
WORKDIR /app

# copy package files and typescript config
COPY package*.json tsconfig.json ./

# install dependencies without running scripts
RUN npm install --ignore-scripts

# copy all source files
COPY . .

# build typescript
RUN npm run build

# expose port if HTTP, but stdio doesn't need expose

# default command
CMD ["node", "dist/index.js"]
